//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGTUTelephone
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepContact
    {
        public int ID { get; set; }
        public string Phone { get; set; }
        public string IP_Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public Nullable<decimal> Rank { get; set; }
        public string IsDep { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
