//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGTUTelephone
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptEmplo
    {
        public int ID { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public Nullable<int> idManagerDepartment { get; set; }
        public string DepartmentName { get; set; }
        public string Employee { get; set; }
        public string Phone { get; set; }
        public string IP_Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<int> pg { get; set; }
        public Nullable<decimal> Rank { get; set; }
        public string Department { get; set; }
        public Nullable<int> Lat { get; set; }
        public Nullable<int> ContactsIDFK { get; set; }
    }
}
